name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build Docker image
      run: docker build -t $DOCKER_USERNAME/myapp:latest .

    - name: Push Docker image
      run: docker push $DOCKER_USERNAME/myapp:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ env.PRIVATE_KEY }}
        script: |
          docker pull $DOCKER_USERNAME/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 80:3000 --name myapp $DOCKER_USERNAME/myapp:latest
